# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8c270236798e9f893f3ccf2ee2b5d13e5ecb58cd675bff28811b8eb6e06be1a1b10ec72fa8a4bb07a48eaaa92738c035f8aa92b4b7d7b7765aee470c509ec98

test:
  secret_key_base: b2d8c060d84d7e346f0533fae1cd1dae905927317ab5881e9f8fb2a661230aacf4319edda9cb2283a074abbffcfac61e49857a05e9b0c64ddd6d64d02f7e9876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
